# Generated by Django 4.0.3 on 2022-04-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('BANK_TYPE', models.CharField(max_length=20)),
                ('VALUE', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CPFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('ACCOUNT_TYPE', models.CharField(max_length=20)),
                ('VALUE', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('ASSET_TYPE', models.CharField(max_length=20)),
                ('VALUE', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('INVESTMENT_TYPE', models.CharField(max_length=50)),
                ('VALUE', models.FloatField()),
            ],
        ),
    ]
