# Generated by Django 4.0.3 on 2022-04-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpfmodel',
            name='ACCOUNT_TYPE',
        ),
        migrations.RemoveField(
            model_name='cpfmodel',
            name='VALUE',
        ),
        migrations.AddField(
            model_name='cpfmodel',
            name='CODE',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpfmodel',
            name='MA',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpfmodel',
            name='OA',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpfmodel',
            name='SA',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpfmodel',
            name='YEARMONTH',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
