# Generated by Django 4.0.3 on 2022-04-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_cpfmodel_id_bankmodel_yearmonth_cpfmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentmodel',
            name='YEARMONTH',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
