# Generated by Django 4.0.3 on 2022-05-02 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_investmentmodel_yearmonth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataModel',
        ),
    ]
