# Generated by Django 4.0.3 on 2022-05-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_datamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpfmodel',
            name='REF',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
