# Generated by Django 4.0.3 on 2022-05-30 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bankmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankModel',
        ),
        migrations.DeleteModel(
            name='CPFModel',
        ),
        migrations.DeleteModel(
            name='DebtModel',
        ),
        migrations.DeleteModel(
            name='InvestmentModel',
        ),
    ]
