# Generated by Django 4.0.3 on 2022-05-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0010_delete_bankmodel_delete_cpfmodel_delete_debtmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('DATE', models.DateField()),
                ('YEARMONTH', models.CharField(max_length=10)),
                ('BANK_TYPE', models.CharField(max_length=20)),
                ('VALUE', models.FloatField()),
                ('HISTORICAL', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CPFModel',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('DATE', models.DateField()),
                ('YEARMONTH', models.CharField(max_length=10)),
                ('CODE', models.CharField(max_length=10)),
                ('REF', models.CharField(max_length=10)),
                ('OA', models.FloatField()),
                ('SA', models.FloatField()),
                ('MA', models.FloatField()),
                ('HISTORICAL', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DebtModel',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('DATE', models.DateField()),
                ('YEARMONTH', models.CharField(max_length=10)),
                ('DEBT_TYPE', models.CharField(max_length=50)),
                ('DEBT_VALUE', models.FloatField()),
                ('INTEREST_RATE', models.FloatField()),
                ('INTEREST_COMPOUND', models.CharField(max_length=20)),
                ('REPAYMENT', models.FloatField()),
                ('INTEREST', models.FloatField()),
                ('REMAINING_VALUE', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentModel',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('DATE', models.DateField()),
                ('YEARMONTH', models.CharField(max_length=10)),
                ('INVESTMENT_TYPE', models.CharField(max_length=50)),
                ('VALUE', models.FloatField()),
                ('HISTORICAL', models.BooleanField(default=False)),
            ],
        ),
    ]
