# Generated by Django 4.0.3 on 2022-08-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefModel',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('RELIEF', models.CharField(max_length=50)),
                ('VALUE', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxModel',
            fields=[
                ('YEAR', models.IntegerField(primary_key=True, serialize=False)),
                ('INCOME', models.FloatField()),
                ('TAX_YEAR', models.FloatField()),
                ('TAX_MONTH', models.FloatField()),
            ],
        ),
    ]
