# Generated by Django 4.0.3 on 2022-08-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_reliefmodel_taxmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliefmodel',
            name='YEAR',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
