# Generated by Django 4.0.3 on 2022-09-18 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_reliefmodel_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentmodel',
            name='DATE',
        ),
        migrations.RemoveField(
            model_name='investmentmodel',
            name='HISTORICAL',
        ),
        migrations.RemoveField(
            model_name='investmentmodel',
            name='INVESTMENT_TYPE',
        ),
    ]
